UpnoidV4/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UpnoidV4.Models
{
    public class Movie
    {
        public int Id { get; set; }
        [Required]
        [StringLength(255)]
        public string Name { get; set; }
        [Display(Name = "Release Date")]
        public string ReleaseDate { get; set; }
      
        public string DateAdded { get; set; }
        
        [Display(Name = "Number in Stock")]
        [Range(1,20)]
        public byte  NumberInStock { get; set; }
      
        public Genre Genre { get; set; }
        [Display(Name = "Genre")]
        [Required]
        public byte GenreId { get; set; }
        public byte NumberAvailable { get; set; }

        [StringLength(100, MinimumLength = 7)]
        public string Description { get; set; }
    }
}

UpnoidV4/Controllers/Api/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using AutoMapper;
using UpnoidV4.Dtos;
using UpnoidV4.Models;

namespace UpnoidV4.Controllers.Api
{
    public class MoviesController : ApiController
    {
        private ApplicationDbContext _context;

        public MoviesController()
        {
            _context = new ApplicationDbContext();
        }
        // GET /api/movies
        public IEnumerable<MovieDto> GetMovies(string query = null)
        {
            var moviesQuery = _context.Movies
                .Include(m => m.Genre)
                .Where(m => m.NumberAvailable > 0);

            if (!String.IsNullOrWhiteSpace(query))
                moviesQuery = moviesQuery.Where(m => m.Name.Contains(query));

            return moviesQuery
                .ToList()
                .Select(Mapper.Map<Movie, MovieDto>);
        }
        // GET /api/movies/1
        public IHttpActionResult GetMovie(int id)
        {
            var movie = _context.Movies.SingleOrDefault(c => c.Id == id);

            if (movie == null)
                return NotFound();

            return Ok(Mapper.Map<Movie, MovieDto>(movie));
        }

        // POST /api/movies
        [HttpPost]
       // [Authorize(Roles = RoleName.CanManageMovies)]
        public IHttpActionResult CreateMovie(MovieDto movieDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var movie = Mapper.Map<MovieDto, Movie>(movieDto);
            _context.Movies.Add(movie);
            _context.SaveChanges();

            movieDto.Id = movie.Id;
            return Created(new Uri(Request.RequestUri + "/" + movie.Id), movieDto);
        }

        // PUT /api/movies/1
        [HttpPut]
       // [Authorize(Roles = RoleName.CanManageMovies)]
        public IHttpActionResult UpdateMovie(int id, MovieDto movieDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var movieInDb = _context.Movies.SingleOrDefault(c => c.Id == id);

            if (movieInDb == null)
                return NotFound();

            Mapper.Map(movieDto, movieInDb);

            _context.SaveChanges();

            return Ok();
        }

        // DELETE /api/movies/1
        [HttpDelete]
       // [Authorize(Roles = RoleName.CanManageMovies)]
        public IHttpActionResult DeleteMovie(int id)
        {
            var movieInDb = _context.Movies.SingleOrDefault(c => c.Id == id);

            if (movieInDb == null)
                return NotFound();

            _context.Movies.Remove(movieInDb);
            _context.SaveChanges();

            return Ok();
        }
    }
}

UpnoidV4/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UpnoidV4.Models;
using UpnoidV4.ViewModels;

namespace UpnoidV4.Controllers
{
    public class MoviesController : Controller
    {
        private ApplicationDbContext _context;

        public MoviesController()
        {
            _context = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        [AllowAnonymous]
        public ActionResult Trailer()
        {
            return Redirect("https://www.youtube.com");
        }

        //trailer

        public ViewResult Indexx()
        {
            return View();
        }

        public ViewResult Index()
        {
            if (User.IsInRole(RoleName.CanManageMovies))
                return View("List");

            return View("ReadOnlyList");
        }

        [Authorize(Roles = RoleName.CanManageMovies)]
        public ViewResult New()
        {
            var genres = _context.Genres.ToList();
            var viewModel = new MovieFormViewModel
            {            
                Genres = genres
            };

            return View("MovieForm", viewModel);
        }

        [Authorize(Roles = RoleName.CanManageMovies)]
        public ActionResult Edit(int id)
        {
            var movie = _context.Movies.SingleOrDefault(c => c.Id == id);

            if (movie == null)
                return HttpNotFound();

            var viewModel = new MovieFormViewModel(movie)
            {
                Genres = _context.Genres.ToList()
            };

            return View("MovieForm", viewModel);
        }


        public ActionResult Details(int id)
        {
            var movie = _context.Movies.Include(m => m.Genre).SingleOrDefault(m => m.Id == id);

            if (movie == null)
                return HttpNotFound();

            return View(movie);

        }


        // GET: Movies/Random
        public ActionResult Random()
        {
            var movie = new Movie() { Name = "Shrek!" };
            var customers = new List<Customer>
            {
                new Customer { Name = "Customer 1" },
                new Customer { Name = "Customer 2" }
            };

            var viewModel = new RandomMovieViewModel
            {
                Movie = movie,
                Customers = customers
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = RoleName.CanManageMovies)]
        public ActionResult Save(Movie movie)
        {
            if (!ModelState.IsValid)
            {
                var viewModel = new MovieFormViewModel(movie)
                {
                    Genres = _context.Genres.ToList()
                };

                return View("MovieForm", viewModel);
            }

            if (movie.Id == 0)
            {
                //added this line
                movie.NumberAvailable = movie.NumberInStock;
                //movie.DateAdded = DateTime.Now;
                _context.Movies.Add(movie);
            }
            else
            {
                var movieInDb = _context.Movies.Single(m => m.Id == movie.Id);
                movieInDb.Name = movie.Name;
                movieInDb.GenreId = movie.GenreId;
                movieInDb.NumberInStock = movie.NumberInStock;
                movieInDb.ReleaseDate = movie.ReleaseDate;
            }

            _context.SaveChanges();

            return RedirectToAction("Index", "Movies");
        }
    }
}

UpnoidV4/Controllers/RentalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using UpnoidV4.Models;
using UpnoidV4.ViewModels;

namespace UpnoidV4.Controllers
{
    public class RentalsController : Controller
    {
        private ApplicationDbContext _context;

        public RentalsController()
        {
            _context = new ApplicationDbContext();
        }
        public ViewResult Index()
        {
            if (User.IsInRole(RoleName.CanManageMovies))
                return View("Index");
       
                return View("Index");
        }
        public ActionResult New()
        {
            if (User.IsInRole(RoleName.CanManageMovies))
            return View("New");

            return View("AccessDenied");
        }
        public ActionResult Details(int id)
        {
            var rental = _context.Rentals.Include(r => r.Movie).Include(r => r.Customer).SingleOrDefault(r => r.Id == id);
            if (rental == null)
                return HttpNotFound();

            return View(rental);
        }
    }
}

UpnoidV4/Views/Movies/Details.cshtml
@model UpnoidV4.Models.Movie
@{
    ViewBag.Title = Model.Name;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Name</h2>
<ul>
    <li>Genre:@Model.Genre.Name</li>
    <li>Release Date: @Model.ReleaseDate</li>
    <li>Date Added: @Model.DateAdded</li>
    <li>Number in Stock: @Model.NumberInStock</li>
</ul>

UpnoidV4/Views/Movies/List.cshtml
@model IEnumerable<UpnoidV4.Models.Movie>

@{
    ViewBag.Title = "Movies";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>List of Movies</h2>
<hr/>
<p>
    @Html.ActionLink("New Movie", "New", "Movies", null, new { @class = "btn btn-primary" })
    @Html.ActionLink("View Rented Movies", "Index", "Rentals", null, new { @class = "btn btn-primary" })
</p>

<table id="movies" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th><div><b>Movie</b></div></th>
            <th><div><b>Genre</b></div></th>
            <th><div><b>Number Available</b></div></th>
            <th><div><b>Delete</b></div></th>

            <th><div><b>Watch Trailer</b></div></th>
            
        </tr>
    </thead>
    <tbody>
       
          
    </tbody>
</table>
@section scripts
{
    <script>
        $(document).ready(function () {
            var table = $("#movies").DataTable({
                lengthMenu: [[5, 6, 10, 25, 50, -1], [5, 6, 10, 25, 50, "All"]],
                pageLenght: 4,
                "bSort": true,
                ajax: {
                    url: "/api/movies",
                    dataSrc: ""
                },
                columns: [
                    {
                        data: "name",
                        render: function(data, type, movie) {
                            return "<a href='/movies/edit/" + movie.id + "'>" + movie.name + "</a>";
                        }
                    },
                    {
                        data: "genre.name"
                    },
                   
                    {
                        data: "numberAvailable"
                    },
                  
                    {
                        data: "id",
                        render: function(data) {
                            return "<button class='btn btn-primary js-delete' data-movie-id=" + data + ">Delete</button>";
                        }
                    },
                    {
                        data: "id",
                        render: function(data) {
                            return "<a href='/movies/trailer/'> Watch Trailer</a>";
                        }
                    },
                  
                   
                ]
            });
            $("#movies").on("click", ".js-delete", function () {
                var button = $(this);

                bootbox.confirm("Are you sure you want to delete this movie?", function (result) {
                    if (result) {
                        $.ajax({
                            url: "/api/movies/" + button.attr("data-movie-id"),
                            method: "DELETE",
                            success: function () {
                                table.row(button.parents("tr")).remove().draw();
                            }
                        });
                    }
                });
            });
        });
    </script>
}

UpnoidV4/Views/Movies/MovieForm.cshtml
@model UpnoidV4.ViewModels.MovieFormViewModel
@{
    ViewBag.Title = "New";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>New Movie</h2>
<hr/>
@using (Html.BeginForm("Save", "Movies"))
{
    @Html.ValidationSummary(true, "Please fix the following errors.")
    <div class="form-group">
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Name)
    </div>

    <div class="form-group" id="datepicker">
        @Html.LabelFor(m => m.ReleaseDate)
        @Html.TextBoxFor(m => m.ReleaseDate, "{0:d MMM yyyy}", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.ReleaseDate)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.GenreId)
        @Html.DropDownListFor(m => m.GenreId, new SelectList(Model.Genres, "Id", "Name"), "Select Genre", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.GenreId)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.NumberInStock)
        @Html.TextBoxFor(m => m.NumberInStock, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.NumberInStock)
    </div>

    @Html.HiddenFor(m => m.Id)
    @Html.AntiForgeryToken()
    <button type="submit" class="btn btn-primary">Save</button>

}
@section scripts
{
    <script>
        $(function () {
            $("#datepicker").datepicker();
        });
    </script>


    @Scripts.Render("~/bundles/jqueryval")
}

UpnoidV4/Views/Movies/Random.cshtml
@model UpnoidV4.ViewModels.RandomViewModel
@{
    ViewBag.Title = "Random";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    var clasName = Model.Customers.Count > 0 ? "popular" : null;
}

<h2 class="@clasName">@Model.Movie.Name</h2>

@if (Model.Customers.Count == 0)
{
    <p>
        No one has rented this movie before.
    </p>
}
else
{
    <ul>

        @foreach (var customer in Model.Customers)
        {
            <li>@customer.Name</li>
        }

    </ul>
}

UpnoidV4/Views/Movies/ReadOnlyList.cshtml
@model IEnumerable<UpnoidV4.Models.Movie>

@{
    ViewBag.Title = "Movies";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Movies</h2>
<p>
    @Html.ActionLink("View Rented Movies", "Index", "Rentals", null, new { @class = "btn btn-primary" })
</p>

<table id="movies" class="table table-bordered table-hover">
    <thead>
    <tr>
        <th><b>Movie</b></th>
        <th><b>Genre</b></th>
        <th><b>Number in Stock</b></th>
        <th><b>Watch Trailer</b></th>     
    </tr>
    </thead>
    <tbody>
    </tbody>
</table>
@section scripts
{
    <script>
        $(document).ready(function () {
            var table = $("#movies").DataTable({
                lengthMenu: [[5, 6, 10, 25, 50, -1], [5, 6, 10, 25, 50, "All"]],
                pageLenght: 4,
                ajax: {
                    url: "/api/movies",
                    dataSrc: ""
                },
                columns: [
                    {
                        data: "name",
                        render: function (data, type, movie) {
                            return "<a href='/movies/details/" + movie.id + "'>" + movie.name + "</a>";
                        }
                    },
                    {
                        data: "genre.name"
                    },
                    {
                        data: "numberInStock"
                    },
                   
                    {
                        data: "id",
                        render: function (data) {
                            return "<a href='/movies/trailer/'> Watch Trailer</a>";
                        }
                    }

                ]
            });
        });
    </script>
}

UpnoidV4/Views/Movies/Reports.cshtml
@model UpnoidV4.Models.Movie
@{
    ViewBag.Title = Model.Name;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Name</h2>


<body>
<div id="columnchart_material" style="width: 800px; height: 500px;"></div>
</body>
@section scripts{
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        google.charts.load('current', { 'packages': ['bar'] });
        google.charts.setOnLoadCallback(drawChart);

        function drawChart() {
            var data = google.visualization.arrayToDataTable([
                ['Year', 'Sales', 'Expenses', 'Profit'],
                ['2014', 1000, 400, 200],
                ['2015', 1170, 460, 250],
                ['2016', 660, 1120, 300],
                ['2017', 1030, 540, 350]
            ]);

            var options = {
                chart: {
                    title: 'Company Performance',
                    subtitle: 'Sales, Expenses, and Profit: 2014-2017',
                }
            };

            var chart = new google.charts.Bar(document.getElementById('columnchart_material'));

            chart.draw(data, google.charts.Bar.convertOptions(options));
        }
    </script>

}